language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t benjamistan/docker-frontend -f Dockerfile.dev .

script:
  - docker run benjamistan/docker-frontend npm run test -- --coverage