language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t benjamistan/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true benjamistan/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  name: "docker-frontend"
  env: "DockerFrontend-env"
  bucket-name: "elasticbeanstalk-eu-west-3-323528688928"
  bucket-path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY